package com.xq.Railway.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 * 
 * 
 * 
 *  管理员信息 。
 * @author XingPanST
 *
 */
@ApiModel(description = "管理员信息")
public class administrator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.aid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
	@ApiModelProperty(value = "id",example="1", position = 0)
    private String aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.aname
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
	
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.aphonenum
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String aphonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.afoundtime
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String afoundtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.aemile
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String aemile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.arole
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String arole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.department
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.lineid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String lineid;
    private String linename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.siteid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String siteid;
    private String sitename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.ausername
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String ausername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.apwd
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String apwd;

    
    
    
    private String jurisdiction;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.aid
     *
     * @return the value of administrator.aid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.aid
     *
     * @param aid the value for administrator.aid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.aname
     *
     * @return the value of administrator.aname
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAname() {
        return aname;
    }

    
    
    public String getLinename() {
		return linename;
	}

	public void setLinename(String linename) {
		this.linename = linename;
	}

	public String getSitename() {
		return sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.aname
     *
     * @param aname the value for administrator.aname
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    
    
    public String getJurisdiction() {
		return jurisdiction;
	}

	public void setJurisdiction(String jurisdiction) {
		this.jurisdiction = jurisdiction;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.aphonenum
     *
     * @return the value of administrator.aphonenum
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAphonenum() {
        return aphonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.aphonenum
     *
     * @param aphonenum the value for administrator.aphonenum
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAphonenum(String aphonenum) {
        this.aphonenum = aphonenum == null ? null : aphonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.afoundtime
     *
     * @return the value of administrator.afoundtime
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAfoundtime() {
        return afoundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.afoundtime
     *
     * @param afoundtime the value for administrator.afoundtime
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAfoundtime(String afoundtime) {
        this.afoundtime = afoundtime == null ? null : afoundtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.aemile
     *
     * @return the value of administrator.aemile
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAemile() {
        return aemile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.aemile
     *
     * @param aemile the value for administrator.aemile
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAemile(String aemile) {
        this.aemile = aemile == null ? null : aemile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.arole
     *
     * @return the value of administrator.arole
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getArole() {
        return arole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.arole
     *
     * @param arole the value for administrator.arole
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setArole(String arole) {
        this.arole = arole == null ? null : arole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.department
     *
     * @return the value of administrator.department
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.department
     *
     * @param department the value for administrator.department
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.lineid
     *
     * @return the value of administrator.lineid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.lineid
     *
     * @param lineid the value for administrator.lineid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setLineid(String lineid) {
        this.lineid = lineid == null ? null : lineid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.siteid
     *
     * @return the value of administrator.siteid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.siteid
     *
     * @param siteid the value for administrator.siteid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid == null ? null : siteid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.ausername
     *
     * @return the value of administrator.ausername
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getAusername() {
        return ausername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.ausername
     *
     * @param ausername the value for administrator.ausername
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setAusername(String ausername) {
        this.ausername = ausername == null ? null : ausername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.apwd
     *
     * @return the value of administrator.apwd
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getApwd() {
        return apwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.apwd
     *
     * @param apwd the value for administrator.apwd
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setApwd(String apwd) {
        this.apwd = apwd == null ? null : apwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.isdelete
     *
     * @return the value of administrator.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.isdelete
     *
     * @param isdelete the value for administrator.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

	@Override
	public String toString() {
		return "administrator [aid=" + aid + ", aname=" + aname + ", aphonenum=" + aphonenum + ", afoundtime="
				+ afoundtime + ", aemile=" + aemile + ", arole=" + arole + ", department=" + department + ", lineid="
				+ lineid + ", linename=" + linename + ", siteid=" + siteid + ", sitename=" + sitename + ", ausername="
				+ ausername + ", apwd=" + apwd + ", jurisdiction=" + jurisdiction + ", isdelete=" + isdelete + "]";
	}
    
    
}