package com.xq.Railway.model;

import io.swagger.annotations.ApiModelProperty;

/**
 * 
 * 
 * 
 * 站点信息
 * @author XingPanST
 *
 */
public class linesite {
	@ApiModelProperty(hidden=true)
    private String id;

    private String routeid; //关联线路id

    private String sitename;//站点名称
    @ApiModelProperty(hidden=true)
    private String isdelete;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linesite.id
     *
     * @param id the value for linesite.id
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linesite.routeid
     *
     * @return the value of linesite.routeid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linesite.routeid
     *
     * @param routeid the value for linesite.routeid
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linesite.sitename
     *
     * @return the value of linesite.sitename
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linesite.sitename
     *
     * @param sitename the value for linesite.sitename
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linesite.isdelete
     *
     * @return the value of linesite.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linesite.isdelete
     *
     * @param isdelete the value for linesite.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

	@Override
	public String toString() {
		return "linesite [id=" + id + ", routeid=" + routeid + ", sitename=" + sitename + ", isdelete=" + isdelete
				+ "]";
	}
    
}