package com.xq.Railway.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 * 
 * 测量标准
 * @author XingPanST
 *
 */
@ApiModel(description="测量标准-项点标准")
public class measurementstandard {
	
    private String id;
    @ApiModelProperty(value="测量项名称" ,name = "measurementitem",example="轨距", position = 0)
    private String measurementitem;//测量项
    
    @ApiModelProperty(value="是否为系统判断项点 0：手动判断 1：机器判断 id:为轨距关联详细标准" ,name = "state",example="0/1/id", position = 6)
    private String state;//范围
    
    @ApiModelProperty(value="if state:1 ranges:第一个数字 " ,name = "range1",example="1", position = 7)
    private String ranges;//范围
    @ApiModelProperty(value="if state:1 如果有两个数字 ranges:第二个数字" ,name = "range1", example="2",position = 7)
    private String standard;//测量标准
    
    
    @ApiModelProperty(value="if state:0 range1:文字描述  state:1 range1：符号算法id " ,name = "range1", position = 7)
    private String range1;//范围
    
    
    @ApiModelProperty(value="检查意见" ,name = "standard1",example="检查意见", position = 5)
    private String standard1;//测量标准

    private String isdelete;
    @ApiModelProperty(value="道岔标准id" ,name = "turnoutstandardid",example="道岔标准id", position = 1)
    private String turnoutstandardid;//道岔标准id
    
    @ApiModelProperty(value="检查方法和数量" ,name = "inspectionmethod",example="检查方法和数量", position = 2)
    private String inspectionmethod;//检查方法和数量
    
    
    @ApiModelProperty(value="管理类别A/B/C" ,name = "managementcategory",example="A/B/C", position = 3)
    private String managementcategory;//管理类别
    
    @ApiModelProperty(value="是否有详细标准 0：没有 1：有" ,name = "isdetails",example="0/1", position = 4)
    private String isdetails;//管理类别

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    
    
    public String getIsdetails() {
		return isdetails;
	}

	public void setIsdetails(String isdetails) {
		this.isdetails = isdetails;
	}

	public String getInspectionmethod() {
		return inspectionmethod;
	}

	public void setInspectionmethod(String inspectionmethod) {
		this.inspectionmethod = inspectionmethod;
	}

	public String getManagementcategory() {
		return managementcategory;
	}

	public void setManagementcategory(String managementcategory) {
		this.managementcategory = managementcategory;
	}

	public String getRanges() {
		return ranges;
	}

	public void setRanges(String ranges) {
		this.ranges = ranges;
	}

	public String getTurnoutstandardid() {
		return turnoutstandardid;
	}

	public void setTurnoutstandardid(String turnoutstandardid) {
		this.turnoutstandardid = turnoutstandardid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.measurementitem
     *
     * @return the value of measurementstandard.measurementitem
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getMeasurementitem() {
        return measurementitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.measurementitem
     *
     * @param measurementitem the value for measurementstandard.measurementitem
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setMeasurementitem(String measurementitem) {
        this.measurementitem = measurementitem == null ? null : measurementitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.standard
     *
     * @return the value of measurementstandard.standard
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getStandard() {
        return standard;
    }

    
    
    
    
    
    public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRange() {
		return ranges;
	}

	public void setRange(String range) {
		this.ranges = range;
	}

	public String getRange1() {
		return range1;
	}

	public void setRange1(String range1) {
		this.range1 = range1;
	}

	public String getStandard1() {
		return standard1;
	}

	public void setStandard1(String standard1) {
		this.standard1 = standard1;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.standard
     *
     * @param standard the value for measurementstandard.standard
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.isdelete
     *
     * @return the value of measurementstandard.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.isdelete
     *
     * @param isdelete the value for measurementstandard.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}