package com.xq.Railway.model;
/**
 * 
 * 
 * 测量标准
 * @author XingPanST
 *
 */
public class measurementstandard {
    private String id;

    private String measurementitem;//测量项
    
    private String state;//范围

    private String ranges;//范围
    
    private String standard;//测量标准
    
    private String range1;//范围
    
    private String standard1;//测量标准

    private String isdelete;
    
    private String turnoutstandardid;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    
    
    public String getRanges() {
		return ranges;
	}

	public void setRanges(String ranges) {
		this.ranges = ranges;
	}

	public String getTurnoutstandardid() {
		return turnoutstandardid;
	}

	public void setTurnoutstandardid(String turnoutstandardid) {
		this.turnoutstandardid = turnoutstandardid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.measurementitem
     *
     * @return the value of measurementstandard.measurementitem
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getMeasurementitem() {
        return measurementitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.measurementitem
     *
     * @param measurementitem the value for measurementstandard.measurementitem
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setMeasurementitem(String measurementitem) {
        this.measurementitem = measurementitem == null ? null : measurementitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.standard
     *
     * @return the value of measurementstandard.standard
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getStandard() {
        return standard;
    }

    
    
    
    
    
    public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRange() {
		return ranges;
	}

	public void setRange(String range) {
		this.ranges = range;
	}

	public String getRange1() {
		return range1;
	}

	public void setRange1(String range1) {
		this.range1 = range1;
	}

	public String getStandard1() {
		return standard1;
	}

	public void setStandard1(String standard1) {
		this.standard1 = standard1;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.standard
     *
     * @param standard the value for measurementstandard.standard
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurementstandard.isdelete
     *
     * @return the value of measurementstandard.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurementstandard.isdelete
     *
     * @param isdelete the value for measurementstandard.isdelete
     *
     * @mbggenerated Mon Feb 11 12:09:53 CST 2019
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}